### ISSUE TITLE
integer64 does not coerce to matrix correctly

### ISSUE THREAD

**Issue by connorp** [truecluster/bit64#5]
Consider a vector of `integer64`:

```
x <- c(30000, 30000, 250000, 93500, 102900)
x_int64 <- bit64::as.integer64(x)
```

These data do not coerce to matrix correctly, as noted in [this StackOverflow question](https://stackoverflow.com/questions/28262301/how-to-convert-a-data-frame-of-integer64-values-to-be-a-matrix).

```
> as.matrix(x_int64)
#               [,1]
# [1,] 1.482197e-319
# [2,] 1.482197e-319
# [3,] 1.235164e-318
# [4,] 4.619514e-319
# [5,] 5.083935e-319
```

Not entirely sure if this is a bug in base R or in this package, but there seems to be a bug here somewhere.

**Comment by truecluster** [comment]
This
`as.matrix.integer64 <- function (x, ...) {
  if (!is.matrix(x)){
    dim(x) <- c(length(x), 1L)
    dimnames(x) <- if (!is.null(names(x))) list(names(x), NULL) else NULL
  }
  x  
}
`
would theoretically fix _this_ example, and the data.frame-example with _one_ column, but not any data.frames with _more than one_ column. Package bit64 was once thown off CRAN because it had a method `as.vector.integer64`, so I recommend you do this yourself in your code. 
HTH
